#Define install directory
export MYBASEDIR:=/home/gaurav/eclipse-workspace/sls_thesis_project

#Directory for IR to C tool source
IR2CDIR=$(MYBASEDIR)/ir2c

#Directory for back annotation tool source
BADIR=$(MYBASEDIR)/back_annotate