#Define install directory
export MYBASEDIR:=/home/gaurav/eclipse-workspace/pycparser_examples

#Directory for IR to C tool source
IR2CDIR=$(MYBASEDIR)/ir2c

#Directory for back annotation tool source
BADIR=$(MYBASEDIR)/back_annotate

# other tools
PYTHON	= python
RM	= rm
TOUCH	= touch
LN	= ln -s
