# Configuration for cache simulator

# Path to Cache Simulator
CSIM_DIR = /home/gaurav/workspace/hostCompiledSimulation/cache_simulator

# Hardware Model to use
CACHESIM_HWMOD = generic

CACHESIM_HEADERS = $(CSIM_DIR)/headers/
CACHESIM_LIB = $(CSIM_DIR)/lib/
