# Configuration for cache simulator

# Stupid Makefile Issue: Make sure no white space at the end of the variable declarations

# http://stackoverflow.com/questions/18136918/how-to-get-current-directory-of-your-makefile
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
current_dir := $(patsubst %/,%,$(dir $(mkfile_path)))

# Path to Cache Simulator
PEST_DIR := $(current_dir)

POWEREST_SRC = $(PEST_DIR)/src
POWEREST_HEADERS = $(PEST_DIR)/headers/
POWEREST_LIB = $(PEST_DIR)/lib/
